### ISSUE TITLE
小程序开发（问题总结）

### ISSUE THREAD

**Issue by yongheng2016** [yongheng2016/random#14]
1. ~~app.json定义路由，page/index未放在第一个位置，显示的是点击的图片~~
参数路径写重复
2. 图片宽度总是撑开，包括view也是
小程序中的图片默认尺寸：`320x240`（不是`auto`）
直接设置宽度： `width: 300px`
> （开发者说这样设置的原因是：如果设置 auto ，页面布局会因为图片加载的过程有一个闪的现象（例如高度从 0 到 height ），所以要求一定要设置一个宽度和高度。） 
3. 什么时候改用自定义组件，什么时候改用模板？
   3.1 有逻辑的时候用自定义组件，在引入页面内使用
   3.2 UI级的用模板
4. swiper高度自使用问题
 ```class
// 根元素 height：100%；
page {
   height: 100%;
}
```
5. scroll-view 和 swiper 高度冲突
      5.1 `swiper`中的`swiper-item`内嵌套`scroll-view`
      5.2 ~~通过`wx.getSystemInfo`API获取视口高度，动态绑定到`swiper`和`scroll-view`上~~
这种处理方式本质上也是拿到的整个视口的高度，我上面的tab栏占据的高度依然没有解决，可以用`height:100%`解决，徒增代码逻辑
5.2 在`scroll-view`内嵌套一个元素`scroll-contents`，通过设置`scroll-contents`的伪元素和tab栏有关高度的属性都加上，来占据tab栏的高度
+ HTML
```html
<view class="tabContainer">
...
<view/>
<swiper class='swiper' >
  <block wx:for="{{tabText}}">
    <swiper-item class="swiper-item">
      <scroll-view class='scroll-view' scroll-y>
        <view class='scroll-contents'>
          <view wx:for="{{orderData}}" class='order-container'>
            <view></view>
              ...
              ...
        </view>
      <scroll-view>
    <swiper-item>
  <block>
<swiper>
```
+ CSS（`scroll-contents`样式）
```css 
/*根据height世袭高度撑开*/
page {
    height: 100%;
}
/*设置伪元素高度为scroll-contents中所有撑起高度的属性*/
.scroll-contents::before {
    content: '占位';
    display: block;
    font-size: 18px;
    background: transparent;
    padding: 8px;
    color: transparent;
}
```
> (`height: auto`不起作用)
> 微信对css进行了封装，wxss中设置auto作用不到
6. `onLoad`和页面渲染问题，加载的时候先进行了一次渲染
对象不能深入取值
7. `view`本身已经实现了`scroll`功能，`scroll-view`只不过是在特定高度下的`scroll`?
8. animation/自定义组件
在自定义组件内的元素上直接调用animation没作用，应该在引入的自定义组件外套一个`view`，全部作用在此`view`元素上
9. 自定义组件传参，properties什么时机才能收到参数？
组件的生命周期从什么时候开始？
   + 根据组件是否开始渲染来定义是否开始生命周期
   + 当父组件值所传人的值变动时，子组件observer打印出来的数据也随着改变（整个组件实例中的数据也是动态改变的）
